#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os, sys
import json
import argparse
import signal

is_windows = False

try:
   pass
except:
   is_windows = True
   import pyreadline  

def signal_handler(sig, frame):
    print("\n GoodBye!\n")
    sys.exit(0)

def completer(text, state):
    options = [i for i in commands if i.startswith(text)]
    if state < len(options):
       return options[state]
    else:
        return None

def _quit():
   print("Exiting\n")
   sys.exit(0)

#using signal for handling asynchronous events 

signal.signal(signal.SIGINT, signal_handler)
if is_windows:
   pyreadline.Readline().parse_and_bind("tab: complete")
   pyreadline.Readline().set_completer(completer)

parser = argparse.ArgumentParser(description="Get Terminal Art from 80's and 90's")
parser.add_argument('Keyword', type=str, help='Enter the Keyword')
args = parser.parse_args()

def main(Keyword):
   data = json.loads(open ('urls.json').read())
   for k in data:
        for u in k.values():
               if Keyword in u:
                    print(os.system(u))
                    return True
   
   print("Art for this Query not found!")
   _quit()

if __name__ == '__main__': 
   main(args.Keyword) 
